openapi: 3.0.0
info:
  title: API de Usuarios
  version: 1.0.0
  description: API para la gestión de usuarios
paths:
  /users:
    get:
      summary: Obtener todos los usuarios
      description: Recuperar una lista de todos los usuarios
      tags:
        - Users
      responses:
        '200':
          description: Una lista de usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Juan Pérez
                    email:
                      type: string
                      example: juanperez@ejemplo.com
        '500':
          description: Error interno del servidor